"""First revision of models

Revision ID: ae2c87760e2e
Revises: 
Create Date: 2025-05-04 12:16:32.960506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

import app.server.models.dbtables


# revision identifiers, used by Alembic.
revision: str = 'ae2c87760e2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('folders',
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('folder_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.folder_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_index(op.f('ix_folders_folder_path'), 'folders', ['folder_path'], unique=False)
    op.create_table('userapikeys',
    sa.Column('key_id', sa.Uuid(), nullable=False),
    sa.Column('key_permissions', sa.JSON(), nullable=True),
    sa.Column('expiry_date', app.server.models.dbtables.TZDateTime(), nullable=True),
    sa.Column('key_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index(op.f('ix_userapikeys_expiry_date'), 'userapikeys', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_userapikeys_key_data'), 'userapikeys', ['key_data'], unique=False)
    op.create_table('usersessions',
    sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('expiry_date', app.server.models.dbtables.TZDateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_token')
    )
    op.create_index(op.f('ix_usersessions_expiry_date'), 'usersessions', ['expiry_date'], unique=False)
    op.create_table('files',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.folder_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_files_file_path'), 'files', ['file_path'], unique=False)
    op.create_table('deletedfiles',
    sa.Column('delete_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_on', app.server.models.dbtables.TZDateTime(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('delete_id')
    )
    op.create_index(op.f('ix_deletedfiles_deleted_on'), 'deletedfiles', ['deleted_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deletedfiles_deleted_on'), table_name='deletedfiles')
    op.drop_table('deletedfiles')
    op.drop_index(op.f('ix_files_file_path'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_usersessions_expiry_date'), table_name='usersessions')
    op.drop_table('usersessions')
    op.drop_index(op.f('ix_userapikeys_key_data'), table_name='userapikeys')
    op.drop_index(op.f('ix_userapikeys_expiry_date'), table_name='userapikeys')
    op.drop_table('userapikeys')
    op.drop_index(op.f('ix_folders_folder_path'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
