site_name: newguy103-syncserver
site_author: NewGuy103
copyright: "© NewGuy103, 2024. Licensed under the GNU General Public License v3.0."
repo_url: https://github.com/newguy103/syncserver
repo_name: GitHub
edit_uri: blob/main/docs
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

nav:
  - Home: 'index.md'
  - 'Client Module': 'client-interface.md'
  - 'Server API': 'api-overview.md'
  - 'Server Database': 'server-db.md'