name: Run Python tests

on: [push]
permissions:
  contents: read

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86

      - name: Set up Python versions
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests
        uses: pavelzw/pytest-action@510c5e90c360a185039bea56ce8b3e7e51a16507
        with:
          emoji: true
          verbose: true
          job-summary: true
          custom-pytest: source .venv/bin/activate && ./scripts/tests.sh
